CLEDITOR_I18N = {
    "Bold": "Gras", 
    "Italic": "Italique", 
    "Underline": "Souligné", 
    "Strikethrough": "Barré", 
    "Subscript": "Indicé", 
    "Superscript": "Exposant", 
    "Font": "Famille de police", 
    "Text size": "Taille de police", 
    "Style": "Style", 
    "Text color": "Couleur de police", 
    "Highlight color": "Couleur de fond", 
    "Remove formatting": "Effacer la mise en forme", 
    "Unordered list": "Liste à puces", 
    "Ordered list": "Liste numérotée", 
    "Outdent": "Diminuer le retrait", 
    "Indent": "Augmenter le retrait", 
    "Align left": "Aligner à gauche", 
    "Align center": "Aligner au centre", 
    "Align right": "Aligner à droite", 
    "Align full": "Justifier", 
    "Undo": "Annuler la dernière action", 
    "Redo": "Restaurer la dernière action annulée", 
    "Insert horizontal rule": "Insérer une ligne horizontale", 
    "Insert image": "Insérer une image", 
    "Insert link": "Insérer un lien", 
    "Remove link": "Effacer le lien", 
    "Cut": "Couper", 
    "Copy": "Copier", 
    "Paste": "Coller", 
    "Paste as text": "Coller en tant que texte", 
    "Print": "Imprimer", 
    "Show source": "Afficher la source",
    "Paragraph": "Paragraphe",
    "Header 1": "Titre 1",
    "Header 2": "Titre 2",
    "Header 3": "Titre 3",
    "Header 4": "Titre 4",
    "Header 5": "Titre 5",
    "Header 6": "Titre 6",
    "1": "1",
    "2": "2",
    "3": "3",
    "4": "4",
    "5": "5",
    "6": "6",
    "7": "7",
    'Enter URL:': 'entrer l\'URL',
    'Submit': 'soumet',
    "A selection is required when inserting a link.": "Une sélection est nécessaire lors de l'insertion d'un lien.",
    'Paste your content here:': 'Collez votre texte ici:',
    'Press': 'Pressez',
    'Please use keyboard shortcuts': 'Utilisez les raccourcis clavier'
};