CLEDITOR_I18N = { 
    "Bold": "عريض", 
    "Italic": "مائل", 
    "Underline": "تحته خط", 
    "Strikethrough": "فى وسطه خط", 
    "Subscript": "مكتوب تحت الخط", 
    "Superscript": "مكتوب فوق الخط", 
    "Font": "الخط", 
    "Text size": "الحجم", 
    "Style": "تنسيق", 
    "Text color": "لون النص", 
    "Highlight color": "لون الخلفية", 
    "Remove formatting": "إزالة التنسيق", 
    "Unordered list": "قائمة مُنقطة", 
    "Ordered list": "قائمة مُرقمة", 
    "Outdent":"تحريك إلى مستوى أعلى", 
    "Indent": "المسافة البادئة", 
    "Align left": "محاذاة اليسار", 
    "Align center": "محاذاة الوسط ", 
    "Align right": "محاذاة اليمين", 
    "Align full": "محاذاة كاملة", 
    "Undo": "أبطل", 
    "Redo": "فعل ثانية", 
    "Insert horizontal rule": "إدراج خط أفقي", 
    "Insert image": "إدراج صورة", 
    "Insert link": "إدراج الرابط", 
    "Remove link": "إزالة الرابط", 
    "Cut": "فصل", 
    "Copy": "نسخ", 
    "Paste": "لصق", 
    "Paste as text": "لصق كنص", 
    "Print": "طباعة", 
    "Show source": "عرض المصدر",
    "Paragraph": "فقرة",
    "Header 1": "عنوان ١",
    "Header 2": "عنوان ٢",
    "Header 3": "عنوان ٣",
    "Header 4": "عنوان ٤",
    "Header 5": "عنوان ٥",
    "Header 6": "عنوان ٦",
    "1": "١",
    "2": "٢",
    "3": "٣",
    "4": "٤",
    "5": "٥",
    "6": "٦",
    "7": "٧",
    'Enter URL:': 'إدخال الرابط',
    'Submit': 'عرض',
    "A selection is required when inserting a link.": "اختار جزء عند إدراج رابط",
    'Paste your content here:': ':ألصق المحتوى الخاص بك هنا ',
    'Press': 'إضغط',
    'Use keyboard shortcuts': 'استخدم اختصارات لوحة المفاتيح'
};